package com.cobub.server.coprocessor;

import com.cobub.server.coprocessor.autogenerated.Sum;
import com.google.protobuf.RpcCallback;
import com.google.protobuf.RpcController;
import com.google.protobuf.Service;
import org.apache.hadoop.hbase.Cell;
import org.apache.hadoop.hbase.Coprocessor;
import org.apache.hadoop.hbase.CoprocessorEnvironment;
import org.apache.hadoop.hbase.client.Scan;
import org.apache.hadoop.hbase.coprocessor.CoprocessorException;
import org.apache.hadoop.hbase.coprocessor.CoprocessorService;
import org.apache.hadoop.hbase.coprocessor.RegionCoprocessorEnvironment;
import org.apache.hadoop.hbase.protobuf.ResponseConverter;
import org.apache.hadoop.hbase.regionserver.InternalScanner;
import org.apache.hadoop.hbase.util.Bytes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 官网示例：Enpoint
 * 功能：计算员工总薪水(先计算每个region上的员工总薪水,然会汇总所有region结果)
 */
public class SumEndPoint extends Sum.SumService implements Coprocessor, CoprocessorService {

    private static Logger logger = LoggerFactory.getLogger(SumEndPoint.class);

    private RegionCoprocessorEnvironment env;

    @Override
    public Service getService() {
        return this;
    }

    @Override
    public void start(CoprocessorEnvironment env) throws IOException {
        if (env instanceof RegionCoprocessorEnvironment) {
            this.env = (RegionCoprocessorEnvironment) env;
        } else {
            throw new CoprocessorException("Must be loaded on a table region!");
        }
    }

    @Override
    public void stop(CoprocessorEnvironment env) throws IOException {
        // do mothing
    }

    @Override
    public void getSum(RpcController controller, Sum.SumRequest request, RpcCallback done) {
        Scan scan = new Scan();
        scan.addFamily(Bytes.toBytes(request.getFamily()));
        scan.addColumn(Bytes.toBytes(request.getFamily()), Bytes.toBytes(request.getColumn()));
        Sum.SumResponse response = null;
        InternalScanner scanner = null;
        try {
            scanner = env.getRegion().getScanner(scan);
            List<Cell> results = new ArrayList();
            boolean hasMore = false;
            long sum = 0L;
            do {
                hasMore = scanner.next(results);
                logger.info("results.size=" + results.size());
                for (Cell cell : results) {
                    logger.info("family=" + Bytes
                            .toString(cell.getFamilyArray(), cell.getFamilyOffset(), cell.getFamilyLength()));
                    logger.info("column=" + Bytes
                            .toString(cell.getQualifierArray(), cell.getQualifierOffset(), cell.getQualifierLength()));
                    logger.info("value=" + Bytes
                            .toString(cell.getValueArray(), cell.getValueOffset(), cell.getValueLength()));
                    sum = sum + Bytes.toInt(cell.getValueArray(), cell.getValueOffset(), cell.getValueLength());
                }
                logger.info("sum=" + sum);
                results.clear();
            } while (hasMore);

            response = Sum.SumResponse.newBuilder().setSum(sum).build();

        } catch (IOException ioe) {
            ResponseConverter.setControllerException(controller, ioe);
        } finally {
            if (scanner != null) {
                try {
                    scanner.close();
                } catch (IOException ignored) {
                }
            }
        }
        done.run(response);
    }
}